<?php

return [
    [
        'user_id'=>'1',
        'name'=>'Old Wild West',
        'slug'=>'old-wild-west',
        'address'=>'Via Europa, 5',
        'telephone'=>'06 56435 100',
        'email'=>'oldwildwest@gmail.com',
        'p_iva'=>'12343223122',
        'description'=>"'Il ristorante Old Wild West è un luogo che si ispira all'atmosfera e allo stile del Vecchio West Selvaggio. È un ristorante a tema che cerca di ricreare l'esperienza di un saloon dell'epoca, offrendo un'ambientazione rustica e un'atmosfera accogliente. All'interno del ristorante, si possono trovare elementi di arredo tipici del Vecchio West, come tavoli di legno massiccio, sedie di pelle, lampadari in stile rustico e decorazioni a tema western. Il personale potrebbe essere vestito con abiti ispirati all'abbigliamento dei cowboy, aggiungendo un tocco autentico all'esperienza'",
        'opening_hours'=>'12:00AM to 11PM',
        'img'=>'https://antoniodepoli.it/wordpress/wp-content/uploads/2018/10/old-wild-west.jpg',
    ],
    [
        'user_id'=>'2',
        'name'=>'Pizzium',
        'slug'=>'pizzium',
        'address'=>'Via Guglielmo Oberdan, 30',
        'telephone'=>'06 56435 101',
        'email'=>'pizzium@gmail.com',
        'p_iva'=>'12343223123',
        'description'=>"'La specialità del ristorante Pizzium è, ovviamente, la pizza. Il menu offre una varietà di gustose pizze preparate con ingredienti freschi e di alta qualità. Potresti trovare opzioni tradizionali come la margherita, la marinara e la quattro formaggi, così come creazioni più creative con ingredienti innovativi e abbinamenti sorprendenti. Potrebbe essere offerta anche la possibilità di personalizzare la propria pizza scegliendo gli ingredienti preferiti. Oltre alle pizze, il menu del ristorante Pizzium potrebbe includere anche antipasti, insalate fresche e una selezione di dolci deliziosi per concludere il pasto in bellezza.'",
        'opening_hours'=>'12:00AM to 11:30PM',
        'img'=>'https://www.genovatoday.it/~media/horizontal-hi/52659916193115/pizzium-2.jpeg',
    ],
    [
        'user_id'=>'3',
        'name'=>'La Piadineria',
        'slug'=>'la-piadineria',
        'address'=>'Via Marco Polo, 1',
        'telephone'=>'06 56435 102',
        'email'=>'lapiadineria@gmail.com',
        'p_iva'=>'12343223124',
        'description'=>"'La Piadineria si distingue per la sua attenzione alla qualità degli ingredienti, all'artigianalità della preparazione e alla rapidità del servizio. È un luogo ideale per un pasto veloce durante la pausa pranzo o per una cena informale con amici o familiari.  È un'opzione ideale per chi desidera assaporare un piatto tradizionale italiano in modo rapido e conveniente.'",
        'opening_hours'=>'11:00AM to 10:30PM',
        'img'=>'https://www.retailfood.it/wp-content/uploads/2021/01/la-piadineria.jpg',
    ],
    [
        'user_id'=>'4',
        'name'=>'Ca Pelletti',
        'slug'=>"'ca'pelletti'",
        'address'=>'Via Altabella, 15',
        'telephone'=>'06 56435 103',
        'email'=>'capelletti@gmail.com',
        'p_iva'=>'12343223123',
        'description'=>"'Ca'Pelletti è un ristorante caratteristico situato in una pittoresca zona rurale. L'ambiente è rustico e accogliente, con dettagli tradizionali che richiamano la cultura locale. Il ristorante è rinomato per la sua cucina tipica emiliana, che si basa su ingredienti freschi e di alta qualità provenienti dalla regione. Il menu di Ca'Pelletti offre una vasta selezione di piatti tradizionali emiliani, come tortellini, tagliatelle, gnocchi, oltre a una varietà di piatti di carne e di pesce. I piatti sono preparati con cura e presentati in modo appetitoso, offrendo un'esperienza culinaria autentica.'",
        'opening_hours'=>'11:30AM to 11:30PM',
        'img'=>'https://res.cloudinary.com/tf-lab/image/upload/restaurant/d0c2e273-61f0-459e-8b18-46372ba9e640/8f18e9c2-ab70-4ace-a8e5-ffbe55f7439d.jpg',
    ],
    [
        'user_id'=>'5',
        'name'=>'China Express',
        'slug'=>'china-express',
        'address'=>'Via Guglielmo Marconi, 65',
        'telephone'=>'06 56435 104',
        'email'=>'china_express@gmail.com',
        'p_iva'=>'12343223124',
        'description'=>"'China Express è un ristorante specializzato nella cucina cinese, situato in una posizione comoda e accessibile. L'ambiente del ristorante è elegante e moderno, con dettagli che richiamano la cultura cinese. I piatti di China Express sono caratterizzati dall'uso di ingredienti freschi, spezie aromatiche e una combinazione equilibrata di sapori dolci, salati e piccanti. Il ristorante potrebbe offrire anche opzioni vegetariane o vegane per soddisfare le diverse preferenze alimentari dei clienti.'",
        'opening_hours'=>'12:00AM to 11:00PM',
        'img'=>'https://media-cdn.tripadvisor.com/media/photo-s/23/85/7d/ff/the-china-express-outlet.jpg',
    ],
    [
        'user_id'=>'6',
        'name'=>'Tasty Pokè',
        'slug'=>'tasty-pokè',
        'address'=>'Via Guglielmo Marconi, 5',
        'telephone'=>'06 56435 105',
        'email'=>'tasty_poke@gmail.com',
        'p_iva'=>'12343223125',
        'description'=>"'Tasty Poke è un ristorante specializzato nella preparazione di poke bowls, un piatto tradizionale delle isole Hawaii. Situato in un ambiente moderno e informale, Tasty Poke offre un'esperienza culinaria fresca e salutare. Oltre ai poke bowls personalizzati, Tasty Poke potrebbe offrire anche una selezione di piatti di contorno come edamame, tempura di verdure o patatine fritte. Inoltre, potrebbe avere opzioni vegetariane o vegane per adattarsi alle preferenze alimentari dei clienti.'",
        'opening_hours'=>'12:15AM to 11:00PM',
        'img'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJN5DV4AHYcayvSG4q3_YTnBIHodPTnpUj6w&usqp=CAU',
    ],
    [
        'user_id'=>'7',
        'name'=>'Pokè Raimbow',
        'slug'=>'pokè-raimbow',
        'address'=>'Via Guglielmo Marconi, 26',
        'telephone'=>'06 56435 106',
        'email'=>'pokè_raimbow@gmail.com',
        'p_iva'=>'12343223127',
        'description'=>"'Un ristorante poke è un luogo dove puoi gustare deliziosi poke bowls, un piatto di origine hawaiana. L'ambiente di un ristorante poke è solitamente informale e moderno, con un'atmosfera vivace. I poke bowls sono caratterizzati da una combinazione di sapori e texture, con ingredienti freschi e colorati che si uniscono per creare un pasto sano e gustoso. Oltre ai poke bowls, il ristorante poke potrebbe offrire anche altre opzioni come sushi, temaki o insalate di pesce crudo.'",
        'opening_hours'=>'12:30AM to 22:30PM',
        'img'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSagq18g7iGmf3HtDDc2wepNzs--c6FfUFcZtuomWeBJpbwUg8XL_SRIua8Vekq_uVOcys&usqp=CAU',
    ],
    [
        'user_id'=>'8',
        'name'=>'La Corte dei Ghiottoni',
        'slug'=>'la-corte-dei-ghiottoni',
        'address'=>'Via Jacopo della Quercia, 2',
        'telephone'=>'06 56435 107',
        'email'=>'lacortedeighiottoni@gmail.com',
        'p_iva'=>'12343223129',
        'description'=>"'La Corte dei Ghiottoni è un ristorante che si distingue per la sua proposta culinaria di alta qualità e l'attenzione ai dettagli. Situato in un ambiente elegante e accogliente, La Corte dei Ghiottoni offre un'esperienza gastronomica raffinata. L'atmosfera di La Corte dei Ghiottoni è ideale per cene romantiche, incontri d'affari o occasioni speciali. L'arredamento elegante e l'illuminazione soffusa creano un'atmosfera intima e sofisticata.'",
        'opening_hours'=>'12:00AM to 23:30PM',
        'img'=>'https://media-cdn.tripadvisor.com/media/photo-s/0a/fb/af/71/20160422-193001-largejpg.jpg',
    ],
    [
        'user_id'=>'9',
        'name'=>'La Rosa',
        'slug'=>'la-rosa',
        'address'=>'Via Mentana, 10',
        'telephone'=>'06 56435 108',
        'email'=>'la_rosa@gmail.com',
        'p_iva'=>'12343223130',
        'description'=>"'La Rosa è un ristorante accogliente e familiare che offre un'esperienza culinaria tradizionale. Situato in un ambiente caldo e invitante, La Rosa è conosciuto per la sua cucina casalinga e il suo ambiente amichevole. Con una varietà di piatti tradizionali, ingredienti di qualità e un servizio amichevole, La Rosa è il luogo ideale per chi cerca un'esperienza culinaria autentica e piacevole.'",
        'opening_hours'=>'12:00AM to 23:00PM',
        'img'=>'https://www.ristorantedarosa.com/files/.thumbs/home/slider-2022/2000x/da-rosa-ristorante-como-location.jpg',
    ],
    [
        'user_id'=>'10',
        'name'=>'Da Lello',
        'slug'=>'da-lello',
        'address'=>'Via lello, 13',
        'telephone'=>'06 56435 109',
        'email'=>'da_lello@gmail.com',
        'p_iva'=>'12343223131',
        'description'=>"'La trattoria è un accogliente ristorante che si distingue per la sua atmosfera informale e familiare, dove i clienti possono gustare autentiche specialità culinarie locali. Appena varcata la soglia, si viene avvolti da un'atmosfera calda e accogliente, con arredi rustici e dettagli tradizionali che creano un'ambientazione tipica e affascinante. Le ricette sono tramandate di generazione in generazione, mantenendo intatto il gusto autentico della cucina tradizionale. Gli antipasti sfiziosi, i primi piatti saporiti e i secondi piatti ricchi soddisfano i palati più esigenti.'",
        'opening_hours'=>'12:00AM to 22:30PM',
        'img'=>'https://dalello.hu/uploads/dalello-1638170425_2_570x360.jpg',
    ],
    [
        'user_id'=>'11',
        'name'=>'Da Alessandro',
        'slug'=>'da-alessandro',
        'address'=>'Via Alessandor, 67',
        'telephone'=>'06 56435 110',
        'email'=>'da_alessandro@gmail.com',
        'p_iva'=>'12343223132',
        'description'=>"'La trattoria è rinomata per la sua pasta fatta in casa, che viene lavorata con maestria e servita con una selezione di salse e condimenti deliziosi. Tra i piatti più amati vi sono anche le carni alla griglia, le zuppe aromatiche e una vasta scelta di contorni freschi e colorati. Il menù della trattoria offre una varietà di piatti gustosi preparati con ingredienti freschi e di alta qualità provenienti principalmente dalla regione circostante.'",
        'opening_hours'=>'12:30AM to 23:00PM',
        'img'=>'https://media-cdn.tripadvisor.com/media/photo-s/11/1f/bf/79/saletta-romano-cosci.jpg',
    ],
    [
        'user_id'=>'12',
        'name'=>'Da Luca',
        'slug'=>'da-luca',
        'address'=>'Via Luca, 99',
        'telephone'=>'06 56435 111',
        'email'=>'da_luca@gmail.com',
        'p_iva'=>'12343223133',
        'description'=>"'Il ristorante è un accogliente ristorante di quartiere che offre un'esperienza culinaria autentica e genuina. Situata in un ambiente familiare e informale, la trattoria è un luogo dove gli ospiti possono gustare piatti tradizionali preparati con passione e cura. L'attenzione al cliente è una priorità nella trattoria, e lo staff sarà sempre disponibile a consigliarvi sui piatti e ad offrire un servizio cordiale e attento. La combinazione di autenticità culinaria, atmosfera accogliente e servizio di qualità rende la trattoria un luogo ideale per una serata piacevole tra amici o per un pranzo in famiglia.'",
        'opening_hours'=>'12:30AM to 23:00PM',
        'img'=>'https://www.vito.it/wp-content/uploads/2020/06/ristorante.jpg',
    ],
    [
        'user_id'=>'13',
        'name'=>'Da Rosa',
        'slug'=>'da-rosa',
        'address'=>'Via Rosa, 44',
        'telephone'=>'06 56435 113',
        'email'=>'da_rosa@gmail.com',
        'p_iva'=>'12343223134',
        'description'=>"'Il ristorante è un'elegante destinazione gastronomica che offre un'esperienza culinaria raffinata e sofisticata. Situato in un ambiente elegante e ben curato, il ristorante incanta i suoi ospiti con una combinazione di eccellente cucina, servizio impeccabile e un'atmosfera incantevole. Appena varcate le porte del ristorante, sarete accolti da un ambiente raffinato e ben arredato, con una luce soffusa che crea un'atmosfera intima. I tavoli ben apparecchiati, le sedie comode e gli elementi decorativi di gusto contribuiscono a creare un'atmosfera di classe.'",
        'opening_hours'=>'12:00AM to 22:30PM',
        'img'=>'https://www.ristorantedarosa.com/files/.thumbs/menu/ricevimenti/matrimonio/2000x/matrimonio-ristorante-da-rosa-21.jpg',
    ],
    [
        'user_id'=>'14',
        'name'=>'Da Davide', 
        'slug'=>'da-davide',
        'address'=>'Via Davide, 55',
        'telephone'=>'06 56435 114',
        'email'=>'da_davide@gmail.com',
        'p_iva'=>'12343223135',
        'description'=>"'Il ristorante Da Davide è accogliente e familiare che offre un'esperienza culinaria tradizionale. Situato in un ambiente caldo e invitante, La Rosa è conosciuto per la sua cucina casalinga e il suo ambiente amichevole. Con una varietà di piatti tradizionali, ingredienti di qualità e un servizio amichevole, La Rosa è il luogo ideale per chi cerca un'esperienza culinaria autentica e piacevole.'",
        'opening_hours'=>'12:00AM to 22:30PM',
        'img'=>'https://media-cdn.tripadvisor.com/media/photo-s/18/7d/81/68/il-pergolato.jpg',
    ],
    [
        'user_id'=>'15',
        'name'=>'Da Emanuele', 
        'slug'=>'da-emanuele',
        'address'=>'Via Emanuele, 5',
        'telephone'=>'06 56435 115',
        'email'=>'da_emanuele@gmail.com',
        'p_iva'=>'12343223136',
        'description'=>"'Il ristorante di Emanuele è un luogo accogliente e dal carattere familiare, dove i clienti si sentono subito a loro agio. La cucina proposta è varia e di alta qualità, con una particolare attenzione alla freschezza degli ingredienti e alla preparazione artigianale dei piatti. Il menu offre una vasta scelta di specialità locali e piatti internazionali, sapientemente preparati dallo chef Emanuele e dal suo staff. Il personale è cordiale e attento alle esigenze dei clienti, offrendo un servizio professionale e discreto.'",
        'opening_hours'=>'12:30AM to 23:00PM',
        'img'=>'https://media-cdn.tripadvisor.com/media/photo-s/13/ac/c4/ff/bagni-la-bussola.jpg',
    ],
    [
        'user_id'=>'16',
        'name'=>'Piedra del Sol', 
        'slug'=>'piedra-del sol',
        'address'=>'Via Goito, 20',
        'telephone'=>'06 56435 116',
        'email'=>'piedradelsol@gmail.com',
        'p_iva'=>'12343223137',
        'description'=>"'Il ristorante Piedra del Sol è un'oasi culinaria situata in una posizione panoramica e incantevole. Caratterizzato da un'architettura tradizionale e affascinante, questo ristorante offre un'esperienza culinaria autentica e memorabile. Il menu propone una selezione di piatti ispirati alla cucina messicana, con una varietà di antipasti, primi e secondi piatti, tutti preparati con ingredienti freschi e di alta qualità. I sapori intensi e speziati dei piatti messicani sono abbinati a una presentazione creativa e artistica, creando un connubio perfetto per il palato e per gli occhi'",
        'opening_hours'=>'12:00AM to 23:00PM',
        'img'=>'https://res.cloudinary.com/tf-lab/image/upload/restaurant/1d39293d-cbd0-46ae-893a-b1637a52ecdb/3e075b0d-0f65-485f-8e81-bdeafacb728d.jpg',
    ],
    [
        'user_id'=>'17',
        'name'=>'Burrito Zone', 
        'slug'=>'burrito-zone',
        'address'=>'Via Irnerio, 23',
        'telephone'=>'06 56435 117',
        'email'=>'buttitozone@gmail.com',
        'p_iva'=>'12343223138',
        'description'=>"'Il ristorante Burrito Zone è un luogo informale e accogliente, specializzato nella preparazione di burritos gourmet. Situato in una posizione centrale, è il posto ideale per gustare una deliziosa e autentica esperienza culinaria messicana. Il menu offre una vasta selezione di burritos, con una varietà di ripieni che spaziano dalla carne di manzo o pollo alla verdura, accompagnati da salse piccanti e guarnizioni fresche. Oltre ai burritos, il ristorante offre anche altre specialità messicane come nachos, tacos e quesadillas'",
        'opening_hours'=>'12:00AM to 23:00PM',
        'img'=>'https://img-aws.ehowcdn.com/700x/www.onlyinyourstate.com/wp-content/uploads/2018/12/Screen-Shot-2018-12-30-at-12.38.53-AM.png',
    ],
    [
        'user_id'=>'18',
        'name'=>'Moghul', 
        'slug'=>'moghul',
        'address'=>"'Via dell'inferno, 23'",
        'telephone'=>'06 56435 118',
        'email'=>'moghul@gmail.com',
        'p_iva'=>'12343223138',
        'description'=>"'Il ristorante Moghul è una destinazione culinaria unica che offre un'esperienza indiana autentica e raffinata. Situato in una posizione prestigiosa, il ristorante è noto per la sua cucina raffinata e di alta qualità. Il menu propone una vasta gamma di piatti indiani tradizionali, preparati con cura e passione dagli chef esperti. I sapori speziati e aromatici della cucina indiana si fondono in piatti deliziosi, come il pollo tikka masala, l'agnello korma e il pane naan appena sfornato.'",
        'opening_hours'=>'12:00AM to 23:00PM',
        'img'=>'https://media.cylex-italia.it/companies/7008/410/images/-279604902-Ristorante-Indiano-Moghul_144468_large.jpg',
    ],
    [
        'user_id'=>'19',
        'name'=>'Taj Mahal', 
        'slug'=>'taj-mahal',
        'address'=>"'Via Capo di Lucca, 66'",
        'telephone'=>'06 56435 119',
        'email'=>'taj_mahal@gmail.com',
        'p_iva'=>'12343223139',
        'description'=>"'Il ristorante Taj Mahal è un vero gioiello culinario che offre un'esperienza autentica della cucina indiana. Situato in un ambiente elegante e raffinato, il ristorante incanta i suoi ospiti con una combinazione di sapori esotici, servizio impeccabile e un'atmosfera incantevole. Il menu presenta una vasta selezione di piatti tradizionali indiani, preparati con ingredienti freschi e aromatici. I clienti possono deliziarsi con specialità come il pollo tikka masala, l'agnello biryani, il pane naan appena sfornato e una varietà di deliziosi curry. '",
        'opening_hours'=>'12:00AM to 23:00PM',
        'img'=>'https://qul.imgix.net/bd33807e-4ed2-40d9-85c4-28c2c9d6ac03/200764_sld.jpg?auto=format&ch=Viewport-Width%2CWidth%2CDPR',
    ],
    [
        'user_id'=>'20',
        'name'=>'Sushi Yomi', 
        'slug'=>'sushi-yomi',
        'address'=>"'Via delle Cesoia, 8'",
        'telephone'=>'06 56435 120',
        'email'=>'sushiyomi@gmail.com',
        'p_iva'=>'12343223140',
        'description'=>"'Il ristorante Sushi Yomi è un'affascinante destinazione culinaria specializzata nella preparazione e nel servizio di autentico sushi giapponese. Situato in una posizione centrale e accogliente, il ristorante offre un'esperienza gastronomica unica per gli amanti del sushi. L'atmosfera all'interno di Sushi Yomi è elegante e raffinata, con un design moderno e un arredamento minimalista. Le pareti in legno scuro e l'illuminazione soffusa creano un'atmosfera intima e rilassante, perfetta per una cena romantica o un incontro informale tra amici.'",
        'opening_hours'=>'12:00AM to 23:00PM',
        'img'=>'https://www.ristoranteyoma.it/img_up/img/yoma-2.jpg',
    ],
    [
        'user_id'=>'21',
        'name'=>'Castiglione Pizza e cucina', 
        'slug'=>'castiglione-pizza-e-cucina',
        'address'=>"'Via delle Cesoia, 8'",
        'telephone'=>'06 56435 120',
        'email'=>'sushiyomi@gmail.com',
        'p_iva'=>'12343223141',
        'description'=>"'Il ristorante Sushi Yomi è un'affascinante destinazione culinaria specializzata nella preparazione e nel servizio di autentico sushi giapponese. Situato in una posizione centrale e accogliente, il ristorante offre un'esperienza gastronomica unica per gli amanti del sushi. L'atmosfera all'interno di Sushi Yomi è elegante e raffinata, con un design moderno e un arredamento minimalista. Le pareti in legno scuro e l'illuminazione soffusa creano un'atmosfera intima e rilassante, perfetta per una cena romantica o un incontro informale tra amici.'",
        'opening_hours'=>'12:00AM to 23:00PM',
        'img'=>'https://www.ristoranteyoma.it/img_up/img/yoma-2.jpg',
    ],
    [
        'user_id'=>'22',
        'name'=>'La Bella Napoli', 
        'slug'=>'la-bella-napoli',
        'address'=>"'Via San Felice, 40'",
        'telephone'=>'06 56435 121',
        'email'=>'labella_napoli@gmail.com',
        'p_iva'=>'12343223142',
        'description'=>"'Il ristorante Sushi Yomi è un'affascinante destinazione culinaria specializzata nella preparazione e nel servizio di autentico sushi giapponese. Situato in una posizione centrale e accogliente, il ristorante offre un'esperienza gastronomica unica per gli amanti del sushi. L'atmosfera all'interno di Sushi Yomi è elegante e raffinata, con un design moderno e un arredamento minimalista. Le pareti in legno scuro e l'illuminazione soffusa creano un'atmosfera intima e rilassante, perfetta per una cena romantica o un incontro informale tra amici.'",
        'opening_hours'=>'12:15AM to 23:15PM',
        'img'=>'https://www.gluto.it/immagini/locali/2188.jpg',
    ],
    [
        'user_id'=>'23',
        'name'=>'Mareluna', 
        'slug'=>'mareluna',
        'address'=>"'Via Saragozza, 13'",
        'telephone'=>'06 56435 122',
        'email'=>'mareluna@gmail.com',
        'p_iva'=>'12343223143',
        'description'=>"'La pizzeria Mareluna è un vero gioiello per gli amanti della pizza e dei sapori mediterranei. Situata in una posizione privilegiata di fronte al mare, questa accogliente pizzeria offre un'esperienza culinaria unica e indimenticabile. Oltre alle pizze, la pizzeria Mareluna offre anche una varietà di antipasti, insalate e dessert, tutti preparati con cura e attenzione per i dettagli. Potrete accompagnare la vostra pizza con una selezione di vini locali o gustare una birra fresca per completare l'esperienza.'",
        'opening_hours'=>'12:15AM to 23:15PM',
        'img'=>'https://www.gluto.it/immagini/locali/453.jpg',
    ],
    [
        'user_id'=>'24',
        'name'=>'SpaccaNapoli', 
        'slug'=>'spaccanapoli',
        'address'=>"'Via San Vitale, 45'",
        'telephone'=>'06 56435 123',
        'email'=>'spaccanapoli@gmail.com',
        'p_iva'=>'12343223144',
        'description'=>"'La pizzeria Spaccanapoli è un'autentica oasi culinaria che porta i sapori tradizionali della città di Napoli nel cuore di Bologna. Situata in una posizione centrale, questa pizzeria è un luogo accogliente e vivace, che offre un'esperienza gustativa unica. Se siete alla ricerca di un'autentica esperienza di pizza napoletana, la pizzeria Spaccanapoli è il luogo perfetto per deliziare il vostro palato con sapori tradizionali e genuini.'",
        'opening_hours'=>'12:00AM to 23:00PM',
        'img'=>'https://lh3.googleusercontent.com/p/AF1QipMEYL-An3IaWEE3qaf3jG2a-TcpplUIH5g1o672=w1080-h608-p-k-no-v0',
    ],
    [
        'user_id'=>'25',
        'name'=>'Boolean Italia', 
        'slug'=>'boolean-italia',
        'address'=>"'Via Milano, 45'",
        'telephone'=>'06 56435 125',
        'email'=>'boolean_italia@gmail.com',
        'p_iva'=>'12343223147',
        'description'=>"'Il ristorante di Boolean Italia è un'oasi culinaria che offre un'esperienza gastronomica straordinaria in un ambiente elegante e raffinato. Situato in una posizione prestigiosa, questo ristorante è un vero e proprio tempio della gastronomia, dove ogni dettaglio è curato con la massima attenzione per garantire un'esperienza indimenticabile. Che siate amanti della cucina gourmet, intenditori di vini o semplicemente alla ricerca di un'esperienza culinaria straordinaria, il ristorante di lusso è il luogo ideale per immergersi in un mondo di gusto e raffinatezza. Qui potrete gustare piatti unici, serviti con stile e eleganza, in un ambiente esclusivo che vi farà sentire veramente speciali.'",
        'opening_hours'=>'12:00AM to 23:15PM',
        'img'=>'https://i2.res.24o.it/images2010/Editrice/ILSOLE24ORE/ILSOLE24ORE/Online/Immagini/Food/Pregresso/1804/OBLIX-VIEW-1photo-credit-Richard-Southall-@-Emphasis-Photography.jpg',
    ],
];